// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcmbmdtextavejrqccep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbWJtZHRleHRhdmVqcnFjY2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzU1MzEsImV4cCI6MjA2MjYxMTUzMX0.13jo8O04-ewlwJ4FxsmJ4vXJYOZqzYp-lSmRvE92xuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);